### ISSUE TITLE
This plugin is not working

### ISSUE THREAD

**Issue by ReBirth11** [vecheslav/darcula-solid#4]
Hi, Today I just updated Android Studio Arctic Fox (2020.3.1). I installed this theme again but it's not working. please fix it. I can't code properly without this theme.

**Comment by ReBirth11** [comment]
**Update**
The fix will be included in the next minor release of the 2020.3.1 Arctic Fox.
Found From [issue-tracker](https://issuetracker.google.com/issues/194925628#comment4 )

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037
